### ISSUE TITLE
Review - Feb 25, 2019

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/google_earth_fires#2]
## Part 1

- [x] delete files in py directory that are not needed anymore.
- [x] fix images extensions.
- [ ] Sara and I will review 

* for tentative publish data March 11th.

## Part 2
- [x] Start a new repository 'cal_fires' for new work.  Start new notebook that starts to explore data.  Include where you downloaded the data, what the data is, and  ideas on what you want to do with.
